"use client";
import axios from "axios";
import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";




export default function AiPlanPage() {
  const [aiResponse, setAiResponse] = useState("");

  useEffect(() => {
    let token = localStorage.getItem("token");
    const callAiModel = async () => {
      try {
        let res = await axios.get("https://workout-backend-ethn.onrender.com/trainee/ai-plan", {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        setAiResponse(res.data.response || res.data || "");
      } catch (e) {
        console.log(e);
      }
    };
    callAiModel();
  }, []);

  if (!aiResponse) {
    return (
      <div className="flex h-screen items-center justify-center">
        <p className="text-lg font-medium text-gray-500 animate-pulse">
          Loading your AI plan...
        </p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 px-6 py-10">
      <div className="max-w-5xl mx-auto space-y-8">
        <h1 className="text-3xl font-bold text-center text-gray-800">
          Your Personalized AI Fitness Plan
        </h1>
        <p className="text-center text-gray-600">
          Generated by{" "}
          <span className="font-semibold text-blue-600">AI Coach</span> –
          designed for your body & goals 🚀
        </p>

        <div className="bg-white shadow-xl rounded-2xl p-8 border border-gray-200">
          <div className="prose max-w-none prose-blue prose-headings:text-gray-800 prose-p:text-gray-700 prose-li:marker:text-blue-600">
            <ReactMarkdown>
            {aiResponse}
            </ReactMarkdown>
          </div>
          <div className="bg-gradient-to-r from-purple-600 to-pink-500 shadow-lg rounded-2xl p-6 text-white">
            <h2 className="text-2xl font-semibold mb-3">✨ Daily Motivation</h2>
            <p className="text-lg leading-relaxed italic">
              "Consistency beats perfection. Show up, push through, and the
              results will follow."
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
