"use client";
import axios from "axios";
import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";

export default function AiPlanPage() {
  const [aiResponse, setAiResponse] = useState("");

  useEffect(() => {
    let token = localStorage.getItem("token");
    const callAiModel = async () => {
      try {
        let res = await axios.get(
          // "https://workout-backend-ethn.onrender.com/trainee/ai-plan",
          "http://localhost:8080/trainee/ai-plan",
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );

        setAiResponse(res.data.response || res.data || "");
      } catch (e) {
        console.log(e);
      }
    };
    callAiModel();
  }, []);

  if (!aiResponse) {
    return (
      <div className="flex h-screen items-center justify-center">
        <p className="text-xl font-semibold text-gray-600 animate-pulse">
          Loading your AI plan...
        </p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 px-6 py-10">
      <div className="max-w-4xl mx-auto space-y-10">
        {/* Header */}
        <div className="text-center">
          <h1 className="text-4xl font-extrabold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            Your Personalized AI Fitness Plan
          </h1>
          <p className="mt-3 text-gray-600">
            Generated by{" "}
            <span className="font-semibold text-blue-600">AI Coach</span> – built
            just for your body & goals 🚀
          </p>
        </div>

        {/* Main Plan */}
        <div className="bg-white shadow-lg rounded-2xl p-8 border border-gray-100 transition hover:shadow-2xl">
          <div className="prose max-w-none prose-blue prose-headings:text-gray-800 prose-p:text-gray-700 prose-li:marker:text-blue-600">
            <ReactMarkdown>{aiResponse}</ReactMarkdown>
          </div>
        </div>

        {/* Motivation Section */}
        <div className="bg-gradient-to-r from-purple-600 to-pink-500 shadow-lg rounded-2xl p-8 text-white text-center">
          <h2 className="text-2xl font-bold mb-4">✨ Daily Motivation</h2>
          <p className="text-lg leading-relaxed italic">
            "Consistency beats perfection. Show up, push through, and the
            results will follow."
          </p>
        </div>
      </div>
    </div>
  );
}
