import { Toaster } from "react-hot-toast";
import "../globals.css";
import  ProviderWrapper  from "@/app/provider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" reverseOrder={false} />
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
